/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import todo.bean.User;
import todo.bean.Category;
import todo.bean.Task;
import todo.exception.DAOException;

import java.util.*;

public class App {

    public static void main(String[] args) {
        User user1 = new User("lastName1", "firstName1", "login1", "password1");
        User user2 = new User("lastName2", "firstName2", "login2", "password2");
        User user3 = new User("lastName3", "firstName3", "login3", "password3");

        Category category1A = new Category("category1A", user1);
        Category category1B = new Category("category1B", user1);
        Category category1C = new Category("category1C", user1);
        Category category2A = new Category("category2A", user2);
        Category category2B = new Category("category2B", user2);
        Category category2C = new Category("category2C", user2);
        Category category3A = new Category("category3A", user3);
        Category category3B = new Category("category3B", user3);
        Category category3C = new Category("category3C", user3);

        List<Category> categories1A = new ArrayList<>();
        categories1A.add(category1A);
        categories1A.add(category1B);

        List<Category> categories1B = new ArrayList<>();
        categories1B.add(category1B);
        categories1B.add(category1C);

        List<Category> categories1C = new ArrayList<>();
        categories1C.add(category1A);
        categories1C.add(category1C);

        List<Category> categories2A = new ArrayList<>();
        categories2A.add(category2A);
        categories2A.add(category2B);

        List<Category> categories2B = new ArrayList<>();
        categories2B.add(category2B);
        categories2B.add(category2C);

        List<Category> categories2C = new ArrayList<>();
        categories2C.add(category2A);
        categories2C.add(category2C);

        List<Category> categories3A = new ArrayList<>();
        categories3A.add(category3A);
        categories3A.add(category3B);

        List<Category> categories3B = new ArrayList<>();
        categories3B.add(category3B);
        categories3B.add(category3C);

        List<Category> categories3C = new ArrayList<>();
        categories3C.add(category3A);
        categories3C.add(category3C);

        Task task1A = new Task("task1A", "description1A", new Date(), false, user1, categories1A);
        Task task1B = new Task("task1B", "description1B", new Date(), false, user1, categories1B);
        Task task1C = new Task("task1C", "description1C", new Date(), false, user1, categories1C);
        Task task2A = new Task("task2A", "description2A", new Date(), false, user2, categories2A);
        Task task2B = new Task("task2B", "description2B", new Date(), false, user2, categories2B);
        Task task2C = new Task("task2C", "description2C", new Date(), false, user2, categories2C);
        Task task3A = new Task("task3A", "description3A", new Date(), false, user3, categories3A);
        Task task3B = new Task("task3B", "description3B", new Date(), false, user3, categories3B);
        Task task3C = new Task("task3C", "description3C", new Date(), false, user3, categories3C);

        UserDAO userDao = new UserDAO();
        CategoryDAO categoryDao = new CategoryDAO();
        TaskDAO taskDao = new TaskDAO();

        try {
            System.out.println("\nCreate 3 users ");
            userDao.add(user1);
            userDao.add(user2);
            userDao.add(user3);

            System.out.println("\nCreate 3 categories per user ");
            categoryDao.add(category1A);
            categoryDao.add(category1B);
            categoryDao.add(category1C);
            categoryDao.add(category2A);
            categoryDao.add(category2B);
            categoryDao.add(category2C);
            categoryDao.add(category3A);
            categoryDao.add(category3B);
            categoryDao.add(category3C);

            System.out.println("\nCreate 3 tasks per user ");
            taskDao.add(task1A);
            taskDao.add(task1B);
            taskDao.add(task1C);
            taskDao.add(task2A);
            taskDao.add(task2B);
            taskDao.add(task2C);
            taskDao.add(task3A);
            taskDao.add(task3B);
            taskDao.add(task3C);

            showDatabase();

            System.out.println("\nDelete task1A ");
            taskDao.delete(task1A);

            System.out.println("\nDelete 3 category1A ");
            categoryDao.delete(category1A);

            System.out.println("\nDelete user1 ");
            userDao.delete(user1);

            showDatabase();

            System.out.println("\nUpdate user2 ");
            user2.setFirstName("Un autre firstname");
            user2.setLastName("Un autre lastname");
            user2.setLogin("Un autre login");
            user2.setPassword("Un autre password");
            userDao.update(user2);

            System.out.println("\nUpdate task2A ");
            task2A.setDescription("Une autre description");
            task2A.setDone(true);
            task2A.setName("Un autre nom");
            taskDao.update(task2A);

            System.out.println("\nUpdate category2A ");
            category2A.setName("Encore un autre nom");
            categoryDao.update(category2A);

            showDatabase();
        } catch (DAOException e) {
            System.out.println(e.getMessage());
        }

        System.exit(0);
    }

    public static void showDatabase() {
        UserDAO userDao = new UserDAO();
        CategoryDAO categoryDao = new CategoryDAO();
        TaskDAO taskDao = new TaskDAO();

        List<User> users = userDao.findAll();
        List<Category> categories = categoryDao.findAll();
        List<Task> tasks = taskDao.findAll();


        System.out.println("\nUsers");
        for(User user : users) {
            System.out.println(user);
        }
        System.out.println("\nCategories");
        for (Category category : categories) {
            System.out.println(category);
        }
        System.out.println("\nTasks");
        for (Task task : tasks) {
            System.out.println(task);
        }
    }
}
